### ISSUE TITLE
Great Work and one concern about using own data

### ISSUE THREAD

**Issue by RiqiangGao** [PortPy-Project/PortPy#3]
Dear authors, 

Thank you for starting this fantastic work. I noticed that some beam-related data need to be extracted from external software (i.e., Eclipse). If I understand correctly, if users do not have access to the Eclipse system, they can not use PortPy to run their own data?

Thank you again for the open-source effort in radiotherapy.

**Comment by masoudzp** [comment]
Hello Riqiang,
Thanks for your interest and kind words. What you said is correct. At this
point, the user can use the data provided in the package (10 lung patients
now, would expand to 100 very soon). In the future, we plan to integrate
the package with some Monte Carlo dose calculations and other widely used
commercial systems so the user can use their own data set and system.

Best
Masoud

**Comment by RiqiangGao** [comment]
I see. I appreciate the clarification. Also look forward to future versions.
