### ISSUE TITLE
Questions about exporting PortPy data from Eclipse

### ISSUE THREAD

**Issue by yuanyuande** [PortPy-Project/PortPy#5]
Dear authors,
﻿
Thank you for your excellent work. As a beginner in radiotherapy planning, I am wondering how to export PortPy supported data from the Eclipse TPS that I am using. Or is there any method, such as a script, that can export my PortPy dataset from the planning system?
﻿
Best wishes

**Comment by gourav3017** [comment]
Hello @yuanyuande ,
Thank you for your kind words. At this stage, the user can use only the data provided in the package (50 lung patients). However, we will be releasing a script in the next 4-5 months that can extract PortPy data from the planning system. Thank you.

**Comment by yuanyuande** [comment]
Thank you for your reply, I'm looking forward to the updates, and wish you all the best in your work.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PortPy-Project/PortPy"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月10日(星期三) 凌晨0:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PortPy-Project/PortPy] Questions about exporting PortPy data from Eclipse (Issue #5)





 
Hello @yuanyuande ,
 Thank you for your kind words. At this stage, the user can use only the data provided in the package (50 lung patients). However, we will be releasing a script in the next 4-5 months that can extract PortPy data from the planning system. Thank you.

**Comment by ethanio12345** [comment]
Hi all,

Just querying the status of this as I'm quite interested in this project and would love the ability to test against our existing systems. Thanks for all the amazing work you've done so far. :)

**Comment by masoudzp** [comment]
Hi, we're releasing PortPy.proton module by the end of this year and for that, you'll be able to export data for proton therapy if you have Eclipse. For the existing PortPy.photon module, the data export will probably become available sometime next year.
