### ISSUE TITLE
Downsampling beamlets example failed

### ISSUE THREAD

**Issue by lc82111** [PortPy-Project/PortPy#6]
in preprocess_beams, Line 530 `opt_orig_beamlets = np.stack([orig_beamlets[i] for i in b])`
got all input arrays must have the same shape.

**Comment by gourav3017** [comment]
@lc82111 Hi Cong. Let me look into the issue. Might be recent changes to PortPy would have caused this issue. I will let you know soon

**Comment by gourav3017** [comment]
@lc82111 Fixed it. You can pip install or clone the latest version of PortPy (v1.0.4.3). It should work fine. Thank you.

**Comment by lc82111** [comment]
Thanks for the great work.
