### ISSUE TITLE
Consider making mosek an optional requirement

### ISSUE THREAD

**Issue by philsuess** [PortPy-Project/PortPy#9]
Hello,

Installing portpy on python 3.13 fails at the moment because mosek has a requirement "< 3.13".

As it is, this project does not require mosek to be installed, only when actually performing solver calls does it really need to be there.

So, would you consider making it an optional requirement?

**Comment by gourav3017** [comment]
@philsuess Thank you for bringing it to our attention. We will fix it by making it an optional requirement and let you know soon.

**Comment by gourav3017** [comment]
@philsuess I made it optional. You can install the latest version to resolve the issue. Thank you.
